package main

import (
	"fmt"
	"strings"

	"github.com/gosleek/gosleek/internal/display"
	"github.com/pterm/pterm"
)

// printGlobalHelp shows the top-level help with all commands and their summaries.
func printGlobalHelp() {
	pterm.Println()
	pterm.Println(pterm.Bold.Sprint("  用法: gosleek <命令> [参数]"))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  命令:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  scan", "  扫描目标漏洞")
	printHelpRow("  list", "  列出/筛选可用模板")
	printHelpRow("  validate", "  校验模板语法")
	printHelpRow("  replay", "  复放命中的请求（调试用）[Beta]")
	printHelpRow("  version", "  显示版本信息")
	printHelpRow("  help", "  显示帮助信息")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  全局选项:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  -h, --help", "  显示此帮助信息")
	printHelpRow("  -v, --verbose", "  详细输出")
	printHelpRow("  -vv", "  极详细输出")
	pterm.Println()
	pterm.Println(pterm.Bold.Sprint("  快速开始:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println("    " + pterm.LightYellow("gosleek scan -t http://example.com") + "            " + pterm.Gray("# 扫描目标"))
	fmt.Println("    " + pterm.LightYellow("gosleek list") + "                            " + pterm.Gray("# 查看所有模板"))
	fmt.Println("    " + pterm.LightYellow("gosleek validate templates/") + "                 " + pterm.Gray("# 校验模板"))
	fmt.Println("    " + pterm.LightYellow("gosleek version") + "                         " + pterm.Gray("# 版本信息"))
	fmt.Println()
}

// printHelpRow prints a command/flag row with consistent alignment.
func printHelpRow(cmd, desc string) {
	cmdW := 22
	cmdDisp := display.PadRight(cmd, cmdW)
	pterm.Printf("  %s%s\n", cmdDisp, desc)
}

// printScanHelp shows detailed help for the scan command.
func printScanHelp() {
	pterm.Println()
	pterm.Println(pterm.Bold.Sprint("  用法: gosleek scan [选项]"))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  参数:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  -t, --target <url>", "  单个目标 URL (可多次)")
	printHelpRow("  -l, --list <file>", "  目标列表文件（每行一个 URL）")
	printHelpRow("  --stdin", "  从 stdin 读取目标列表（管道输入）")
	printHelpRow("  -T, --templates <dir>", "  模板目录（默认: templates）")
	printHelpRow("  -id, --tid <id>", "  指定漏洞 ID（同时筛选模板和插件）")
	printHelpRow("  --tags <t,t>", "  按标签筛选模板")
	printHelpRow("  --severity <s,s>", "  按严重度筛选 (info,low,medium,high,critical)")
	printHelpRow("  -e, --exclude <id>", "  排除指定模板/插件 ID")
	printHelpRow("  --plugins-only", "  仅使用 Go 插件扫描 (不加载 YAML 模板)")
	printHelpRow("  --plugin <id,id>", "  指定 Go 插件 ID 扫描 (等价 --plugins-only -id)")
	printHelpRow("  --wordlist-dir <dir>", "  wordlist 文件基础目录 (默认: wordlists)")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  输出:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  -v", "  详细输出（每步进度、跳过原因、信息提示）")
	printHelpRow("  -vv", "  极详细输出（每个请求/响应详情、matcher 命中细节）")
	printHelpRow("  --silent", "  静默模式（仅输出命中结果）")
	printHelpRow("  -o, --output <file>", "  结果写入文件")
	printHelpRow("  -f, --format <fmt>", "  输出格式: json, txt, sarif, html, csv, markdown")
	printHelpRow("  --output-dir <dir>", "  结果输出目录（自动生成时间戳文件名）")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  网络:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  -c, --concurrency <n>", "  并发数（默认: 25）")
	printHelpRow("  -r, --rate-limit <n>", "  每秒请求限制（默认: 150）")
	printHelpRow("  --timeout <s>", "  请求超时秒数（默认: 10）")
	printHelpRow("  -p, --proxy <url>", "  HTTP/SOCKS5 代理 (支持认证)")
	printHelpRow("  -k, --verify-ssl", "  启用 TLS 证书校验 (默认: 跳过)")
	printHelpRow("  --follow-redirects", "  全局跟随重定向")
	printHelpRow("  -H, --header <k:v>", "  全局请求头注入 (可多次)")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  OOB:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  --oob", "  启用 OOB 占位符")
	printHelpRow("  --oob-provider <p>", "  OOB 提供商: ceye(默认) / dnslog / callbackred")
	printHelpRow("  --ceye-key <key>", "  ceye.io API Token")
	printHelpRow("  --ceye-domain <domain>", "  ceye.io 识别域名（如 abc.ceye.io）")
	printHelpRow("  --allow-external-hosts", "  允许 Host 头重定向到外部主机（OOB 必须开启）")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  其他:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	printHelpRow("  --resume <file>", "  从保存的状态断点续扫")
	printHelpRow("  --log-file <file>", "  将结构化日志以 JSON 写入指定文件")
	printHelpRow("  --log-level <level>", "  日志最小级别: debug/info/warn/error (默认随 -v/-vv 自动)")
	printHelpRow("  --filter-severity <s,s>", "  结果过滤: 仅保留指定严重度")
	printHelpRow("  --filter-tags <t,t>", "  结果过滤: 仅保留指定标签")
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println()
	pterm.Println(pterm.Bold.Sprint("  示例:"))
	pterm.Println(pterm.Gray(strings.Repeat("─", 75)))
	fmt.Println("    " + pterm.White("gosleek scan -t http://example.com") + "                              " + pterm.Gray("# 全量扫描"))
	fmt.Println("    " + pterm.White("gosleek scan -t http://example.com -id CVE-2021-44228-log4j-rce") + "  " + pterm.Gray("# 指定漏洞"))
	fmt.Println("    " + pterm.White("gosleek scan -l targets.txt -vv -o results.json") + "                  " + pterm.Gray("# 批量扫描"))
	fmt.Println("    " + pterm.White("gosleek scan -t http://example.com --oob --oob-provider dnslog") + "    " + pterm.Gray("# OOB 验证"))
	fmt.Println("    " + pterm.White("gosleek scan --plugin CVE-2022-22963-go") + "                         " + pterm.Gray("# 仅用指定插件"))
	fmt.Println()
}
